name: simple_responsive_layout
description: "A super lightweight Flutter package for simple mobile, tablet, and desktop responsive layouts."
version: 1.0.1
homepage: https://github.com/philsnook/simple_responsive_layout
repository: https://github.com/philsnook/simple_responsive_layout
issue_tracker: https://github.com/philsnook/simple_responsive_layout/issues

topics:
  - responsive
  - layout
  - flutter
  - adaptive
  - mobile

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
